apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-to-k8s
  namespace: tekton-ci
spec:
  params:
    - name: image
      description: The full image name with tag.
      type: string
  steps:
    - name: patch-deployment
      image: bitnami/kubectl:latest
      script: |
        #!/bin/sh
        set -e
        echo "🔄 Deploying image $(params.image) to ip-viewer-app"
        kubectl set image deployment/testing testing=$(params.image) -n default
        kubectl rollout status deployment/testing -n default

