apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-cd-pipeline
  namespace: tekton-ci
spec:
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
    - name: image-name
      type: string
    - name: dockerfile-path
      type: string
      default: "./Dockerfile"
    - name: build-context
      type: string
      default: "."
  workspaces:
    - name: source-workspace
    - name: docker-config
  tasks:
    - name: clone-repo
      taskRef:
        name: simple-git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: source-workspace

    - name: build-and-push
      runAfter:
        - clone-repo
      taskRef:
        name: buildah-build-push
      params:
        - name: IMAGE_NAME
          value: $(params.image-name)
        - name: COMMIT_SHA
          value: $(tasks.clone-repo.results.commit)
        - name: DOCKERFILE
          value: $(params.dockerfile-path)
        - name: CONTEXT
          value: $(params.build-context)
      workspaces:
        - name: source
          workspace: source-workspace
        - name: dockerconfig
          workspace: docker-config

    - name: deploy
      runAfter:
        - build-and-push
      taskRef:
        name: deploy-to-k8s
      params:
        - name: image
          value: "$(params.image-name):$(tasks.build-and-push.results.SHORT_TAG)"

