apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testing
  template:
    metadata:
      labels:
        app: testing
    spec:
      containers:
        - name: testing
          image: dipakrasal2009/testing:fa244a01  # will be patched to new tag by CD pipeline
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: testing
  namespace: default
spec:
  type: NodePort                    # Change this line to NodePort
  selector:
    app: testing
  ports:
    - port: 80                     # Service port
      targetPort: 8090             # Container port
      # Optional: specify nodePort (value between 30000-32767)
      # nodePort: 30080
