apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testing
  template:
    metadata:
      labels:
        app: testing
    spec:
      containers:
        - name: testing
          image: dipakrasal2009/testing:fa244a01  # will be patched to new tag by CD pipeline
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: testing
  namespace: default
spec:
  selector:
    app: testing
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP

