apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: simple-git-clone
  namespace: tekton-ci
  labels:
    app.kubernetes.io/version: "1.0"
  annotations:
    tekton.dev/pipelines.minVersion: "0.17.0"
    tekton.dev/categories: Git
    tekton.dev/tags: git
    tekton.dev/displayName: "Simple Git Clone (Alpine)"
spec:
  description: >-
    This Task clones a repo from the provided URL using alpine/git image.
    This is a simple, reliable alternative that avoids authentication issues
    with Tekton's official git-init images.
  params:
    - name: url
      description: Repository URL to clone from.
      type: string
    - name: revision
      description: Revision to checkout (branch, tag, sha, ref, etc...)
      type: string
      default: "main"
    - name: deleteExisting
      description: Clean out contents before cloning.
      type: string
      default: "true"
    - name: verbose
      description: Enable verbose logging.
      type: string
      default: "true"
  results:
    - name: commit
      description: The precise commit SHA that was fetched.
    - name: url
      description: The precise URL that was fetched.
  workspaces:
    - name: output
      description: The git repo will be cloned onto this workspace.
  steps:
    - name: clone
      image: alpine/git:latest  # Using reliable alpine/git image
      workingDir: /workspace
      script: |
        #!/bin/sh
        set -e

        if [ "$(params.verbose)" = "true" ]; then
          set -x
        fi

        CHECKOUT_DIR="$(workspaces.output.path)"

        echo "ðŸ” Repository URL: $(params.url)"
        echo "ðŸ“‹ Revision: $(params.revision)"
        echo "ðŸ“ Checkout Directory: $CHECKOUT_DIR"

        # Clean existing directory if requested
        if [ "$(params.deleteExisting)" = "true" ] && [ -d "$CHECKOUT_DIR" ]; then
          echo "ðŸ§¹ Cleaning existing directory..."
          rm -rf "$CHECKOUT_DIR"/*
          rm -rf "$CHECKOUT_DIR"/.[!.]*
          rm -rf "$CHECKOUT_DIR"/..?*
        fi

        # Clone the repository
        echo "ðŸ“¥ Cloning repository..."
        git clone "$(params.url)" --branch "$(params.revision)" --single-branch "$CHECKOUT_DIR"

        # Change to the cloned directory
        cd "$CHECKOUT_DIR"

        # Get the commit SHA
        COMMIT_SHA=$(git rev-parse HEAD)
        echo "ðŸ“ Commit SHA: $COMMIT_SHA"

        # Save results
        echo -n "$COMMIT_SHA" > /tekton/results/commit
        echo -n "$(params.url)" > /tekton/results/url

        echo "âœ… Successfully cloned repository"
        echo "ðŸ“Š Repository info:"
        echo "   URL: $(params.url)"
        echo "   Branch/Tag: $(params.revision)"
        echo "   Commit: $COMMIT_SHA"
        echo "   Files: $(ls -la $CHECKOUT_DIR | wc -l) items"
---