apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-triggers-interceptors-binding
subjects:
- kind: ServiceAccount
  name: ci-pipeline-sa
  namespace: tekton-ci
roleRef:
  kind: ClusterRole
  name: tekton-triggers-core-interceptors
  apiGroup: rbac.authorization.k8s.io
