apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-webhook-listener
  namespace: tekton-ci
  labels:
    app: github-webhook-listener
spec:
  serviceAccountName: ci-pipeline-sa
  triggers:
    - name: github-push-trigger
      bindings:
        - ref: github-push-binding
      template:
        ref: github-push-template
      interceptors:
        - name: "validate-github-payload"
          ref:
            name: "github"
          params:
            - name: "secretRef"
              value:
                secretName: github-webhook-secret
                secretKey: secretToken
            - name: "eventTypes"
              value: ["push"]
        - name: "only-main-branch"
          ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.ref == 'refs/heads/main'"  # Only trigger on main branch pushes
---
apiVersion: v1
kind: Service
metadata:
  name: el-github-webhook-listener
  namespace: tekton-ci
  labels:
    app: github-webhook-listener
spec:
  selector:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: github-webhook-listener
  ports:
    - name: http-listener
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
---
